### ISSUE TITLE
echarts 中加载离线地图

### ISSUE THREAD

**Issue by wonderFF** [wandergis/leaflet-echarts3#7]
你好 问一下 有办法在 echarts 中加载离线地图吗  因为有的项目需要部署到客户的内网环境中 客户又不愿意接受自带的地图

**Comment by wandergis** [comment]
leaflet可以加载离线地图，您可以将下载好的瓦片地图托管到web服务器，使用{z}/{x}/{y}来加载本地托管的地图瓦片

**Comment by wonderFF** [comment]
thank you
